version: '3'

services:
  app:
    build:
      context: .
    image: ${DOCKERHUB_CREDENTIALS_USR}/final-supermarket-web-main:latest 
    container_name: final-supermarket-web-main
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/final-supermarket-web-main
    volumes:
      - .:/var/www/final-supermarket-web-main/
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini 
    networks:
      - final-supermarket-web-main

  webserver:
    image: nginx:alpine
    container_name: nginxfinal-supermarket-web-main
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"  
    volumes:
      - .:/var/www/final-supermarket-web-main
      - ./storage/nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - final-supermarket-web-main

  db:
    image: mysql:5.7
    container_name: dbfinal-supermarket-web-main
    restart: always
    tty: true
    ports:
      - "3308:3306" 
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: audit123
      MYSQL_DATABASE: project_KomputasiAwan_final
    networks:
      - final-supermarket-web-main

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmafinal-supermarket-web-main
    links:
      - db
    restart: always
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - final-supermarket-web-main

networks:
  final-supermarket-web-main:
    driver: bridge

volumes:
  lbdata:
    driver: local
